### ISSUE TITLE
'object of type 'NoneType' has no len()' (adfs portal)

### ISSUE THREAD

**Issue by jbpratt** [cshamrick/stsauth#59]
```
Credentials for the following profile are still valid:
~~~~~~~~~~~

Would you like to continue? [y/N]: y
Traceback (most recent call last):
  File "/home/jbpratt/.local/bin/stsauth", line 8, in <module>
    sys.exit(cli())
  File "/home/jbpratt/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jbpratt/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/sts_auth/cli.py", line 84, in authenticate
    saml_response = sts_auth.get_saml_response()
  File "/home/jbpratt/.local/lib/python3.8/site-packages/sts_auth/stsauth.py", line 161, in get_saml_response
    form_response = self.authenticate_to_adfs_portal(response)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/sts_auth/stsauth.py", line 221, in authenticate_to_adfs_portal
    if login_error_message and len(login_error_message.string) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by phillipjf** [comment]
hey @jbpratt , I know this issue has been open awhile..can you confirm if it is resolved with a newer release?

**Comment by jbpratt** [comment]
Hi @phillipjf I'm not sure whether this has been resolved, I no longer use this tool. Going to go ahead an close the issue, feel free to reopen.
